version: "2"
# Checks are enabled by default, uncomment lines to disable check.
# checks:
#   argument-count:
#     enabled: false
#   complex-logic:
#     enabled: false
#   file-lines:
#     enabled: false
#   method-complexity:
#     enabled: false
#   method-count:
#     enabled: false
#   method-lines:
#     enabled: false
#   nested-control-flow:
#     enabled: false
#   return-statements:
#     enabled: false
#   similar-code:
#     enabled: false
#   identical-code:
#     enabled: false
plugins:
  rubocop:
    enabled: true
    channel: rubocop-1-30-0
  # coffeelint:
  #   enabled: true
  scss-lint:
    enabled: true
  fixme:
    enabled: true
exclude_patterns:
- "app/assets/images/**/*"
- "app/assets/javascripts/external/**/*"
- "bin/**/*"
- "config/**/*"
- "db/**/*"
- "lib/**/*"
- "public/**/*"
- "test/**/*"
- "vendor/**/*"
- "CHANGELOG.md"
- "config.ru"
- "LICENSE"
- "PREREQUISITES.md"
- "Rakefile"
- "README.md"
